
## spring 2.4 이후에는 group

spring:
  profiles:
    group:
      "dev": "localdb, common"

---
spring:
  profiles:
    group:
      "test": "h2db, common"

---
spring:
  profiles:
    group:
      "h2test": "h2db"

---

spring:
  profiles:
    group:
      "prod": "ec2db, common"

---

#spring:
#  config:
#    activate:
#      on-profile: "common"
#
#  jpa:
#    database: mysql
#    hibernate:
#      #  dialect : org.hibernate.dialect.MySQL57Dialect // spring boot make dialect automatically?
#      ddl-auto: validate
#    properties:
#      hibernate:
#        default_batch_fetch_size: 100
#        #        show_sql: true
#        format_sql: true
#
#logging.level:
#  com.B305: DEBUG
#  org.hibernate.SQL: debug
## org.hibernate.type: trace
#
#server:
#  port: 8081
#
#
#---
#
#spring:
#  config:
#    activate:
#      on-profile: "localdb"
#  datasource:
#    url: jdbc:mysql://localhost:3306/ssafy_web_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
##    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: root
#  sql:
#    init:
#      mode: always
#      encoding: utf-8
#  cache:
#    type: redis
#  redis:
#    lettuce:
#      pool:
#        max-active: 10
#        max-idle: 10
#        min-idle: 2
#    cache:
#      host: localhost
#      port: 6379
#    token:
#      host: localhost
#      port: 6380
#    blacklist:
#      host: localhost
#      port: 6381

---

#spring:
##  config:
###    activate:
##      on-profile: "h2db"
#  datascoure:
#    url: jdbc:h2:tcp://localhost/~/test
#    password:
#    driver-class-name: org.h2.Driver
#  jpa:
#    hibernate:
#      ddl-auto: createSELECT * FROM AUTHORITY
#    properties:
#      hibernate:
#        # show_sql : true
#        format_sql: true


# spring.redis.port
---

spring :
  config:
    active:
        on-profile: "h2db"
  redis:
    port: 6379
    host: localhost
  datasource:
    url : jdbc:h2:tcp://localhost/~/test
    username : sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate :
        #    show_sql : true // sout 으로 출력
        format_sql : true

logging:
  level:
    org.hibernate.SQL : debug
    org.hibernate.type : trace
